local_costmap:
  global_frame: map
  robot_base_frame: base_link
  update_frequency: 5.0
  publish_frequency: 4.0
  rolling_window: true

  width: 7
  height: 7 
  origin_x: -3.5
  origin_y: -3.5

  resolution: 0.05
  transform_tolerance: 0.25
  
  plugins:
    - {name: static_layer,        type: "costmap_2d::StaticLayer"}
    - {name: obstacle_layer,      type: "costmap_2d::VoxelLayer"}
    - {name: inflation_layer,     type: "costmap_2d::InflationLayer"}

