TrajectoryPlannerROS:
  max_vel_x: 0.4
  min_vel_x: 0.01
  max_vel_theta: 1.2
  min_vel_theta: -1.2
  min_in_place_vel_theta: 0.60

  acc_lim_theta: 0.3
  acc_lim_x: 0.15
  acc_lim_Y: 1.5

  holonomic_robot: false

  meter_scoring: true

  xy_goal_tolerance: 0.1
  yaw_goal_tolerance: 0.05
